### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Zc0812** [CAS-SIAT-XinHai/CPsyCoun#2]
您好！请教一下！
您论文中提到所有的数据是从真实的心理咨询报告中获得的。
但是数据集中，心理咨询师的回复，有类似GPT的回复逻辑（首先，其次，然后，最后），比较好奇中间经过了怎样的数据处理过程？
谢谢！

![image](https://github.com/user-attachments/assets/ee3bc999-4fbe-4f9c-83c8-7e521172b7c6)
![image](https://github.com/user-attachments/assets/9449ce20-791d-47a5-ab85-618f79aef941)

**Comment by MING-ZCH** [comment]
hi你好，具体流程如下：
我们搜集了真实心理咨询报告CPsyCounR，其中不包含具体咨询对话。因此我们使用Memo2Demo两阶段对话重构方法（**选择使用GLM-4模型**）来生成的多轮咨询对话，详见`code`，进一步人工质检才得到的多轮对话数据集CPsyCounD。
因此可能少量对话会存在该回复形式，我们认为这也是一种有效的回复逻辑，较为简洁😄同时混合训练也可提高模型逻辑能力

![image](https://github.com/user-attachments/assets/eab19b2d-aea7-4440-b48d-c58d9f9483d5)
