### ISSUE TITLE
真实对话

### ISSUE THREAD

**Issue by jkkl** [CAS-SIAT-XinHai/CPsyCoun#5]
好奇问一下，真实的咨询报告都拿到了，真实的对话记录获取不到吗？与咨询师来访者签协议购买，也拿不到吗？

**Comment by jkkl** [comment]
看到生成的 对话，还是明显的有机器的味道，跟真实的咨询相去甚远

**Comment by MING-ZCH** [comment]
> 好奇问一下，真实的咨询报告都拿到了，真实的对话记录获取不到吗？与咨询师来访者签协议purchase，也拿不到吗？

hi你好，感谢你的提问！
过去的工作大多聚焦于单轮QA对话生成多轮对话以及咨询录音转文本，我们的动机之一是想为社区**拓展咨询对话数据集的来源**，因此并未考虑使用真实对话记录，而CPsyCounD数据集完全是由真实咨询报告作为基准生成。
至于你说提到的真实对话记录是否可取得，是需要权衡来访者隐私、团队资源等多重因素，并不在本篇论文讨论范围内。

**Comment by MING-ZCH** [comment]
> 看到生成的 dialog，还是明显的有机器的味道，跟真实的咨询相去甚远

现有模型在模仿真实场景对话还有所欠缺，但通过本文方法(*Memo2Demo*)+强模型生成的对话能达到较为不错的效果(已得到多位相关从业人员的肯定)，同时我们相信随着通用模型的增强，本文方法(*Memo2Demo*)的实用性会得到更大提升~

**Comment by jkkl** [comment]
> > 好奇问一下，真实的咨询报告都拿到了，真实的对话记录获取不到吗？与咨询师来访者签协议purchase，也拿不到吗？
> 
> hi你好，感谢你的提问！ 过去的工作大多聚焦于单轮QA对话生成多轮对话以及咨询录音转文本，我们的动机之一是想为社区**拓展咨询对话数据集的来源**，因此并未考虑使用真实对话记录，而CPsyCounD数据集完全是由真实咨询报告作为基准生成。 至于你说提到的真实对话记录是否可取得，是需要权衡来访者隐私、团队资源等多重因素，并不在本篇论文讨论范围内。

感谢回复~
